//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiGK_63135741.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ThiGK_63135741Entities1 : DbContext
    {
        public ThiGK_63135741Entities1()
            : base("name=ThiGK_63135741Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DocGia> DocGias { get; set; }
        public virtual DbSet<LoaiDocGia> LoaiDocGias { get; set; }
    
        public virtual int TimKiem(string maDG, string hoTen, string maLoaiDG)
        {
            var maDGParameter = maDG != null ?
                new ObjectParameter("MaDG", maDG) :
                new ObjectParameter("MaDG", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var maLoaiDGParameter = maLoaiDG != null ?
                new ObjectParameter("MaLoaiDG", maLoaiDG) :
                new ObjectParameter("MaLoaiDG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TimKiem", maDGParameter, hoTenParameter, maLoaiDGParameter);
        }
    }
}
